# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
  # name: media-pv
# spec:
  # storageClassName: standard
  # capacity:
    # storage: 50Gi
  # volumeMode: Filesystem
  # accessModes:
    # - ReadWriteMany
  # hostPath:
    # path: "/mnt/mediavolume"
    # type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  # hostPath:
    # path: "/mnt/mediavolume"
    # type: DirectoryOrCreate
  nfs:
    path: "/var/nfs_share"
    server: 192.168.1.250

## media.persistentvolumeclaim
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
  # namespace: home-media
  # name: media-pv-claim
# spec:
  # volumeName: media-pv
  # storageClassName: standard
  # accessModes:
    # - ReadWriteMany
  # resources:
    # requests:
      # storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: home-media
  name: nfs-media-pv-claim
spec:
  volumeName: nfs-media-pv
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
