---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mediavolume"
    type: DirectoryOrCreate

## media.persistentvolumeclaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: home-media
  name: media-pv-claim
spec:
  volumeName: media-pv
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
