apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: home-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels: 
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 7878
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          volumeMounts:
            - name: "media-pv"
              mountPath: /config
              subPath: configs/radarr #path /mnt/mediavolume/configs/radarr where radarr writes the configurations
            - name: "media-pv"
              mountPath: /downloads/transmission
              subPath: downloads/transmission # path /mnt/mediavolume/downloads/transmission where radarr picks up downloaded movies
            - name: "media-pv"
              mountPath: /downloads/complete
              subPath: downloads/complete # path /mnt/mediavolume/downloads/transmission where radarr picks up downloaded movies
            - name: "media-pv"
              mountPath: /movies
              subPath: library/movies # path /mnt/mediavolume/library/movies where radarr moves and renames the episodes
            - name: "mounted-network-share"
              mountPath: /mnt/pandoraserver/video
            - name: "mounted-mediajunk-network-share"
              mountPath: /mnt/mediajunk/video
      volumes:
        - name: "media-pv"
          persistentVolumeClaim:
            claimName: media-pv-claim
        - name: "mounted-network-share"
          hostPath:
            path: /mnt/pandoraserver/video
        - name: "mounted-mediajunk-network-share"
          hostPath:
            path: /mnt/mediajunk/video
