apiVersion: v1
kind: Service
metadata:
  name: jackett-service
  # labels:
    # app: sonarr
    # kubernetes.io/name: "sonarr"
spec:
  selector:
    app: jackett
  ports:
  - port: 80
    targetPort: 9117
    protocol: TCP
  type: LoadBalancer
