apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission
  name: transmission
  namespace: home-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels: 
        app: transmission
    spec:
      containers:
        - name: transmission-container
          image: linuxserver/transmission
          imagePullPolicy: IfNotPresent
          ports: 
            - name: web-port
              containerPort: 9091
            - name: torrent-tcp
              protocol: TCP
              containerPort: 51413
            - name: torrent-udp
              protocol: UDP
              containerPort: 51413
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TRANSMISSION_DOWNLOAD_DIR
              value: "/downloads/transmission"
          volumeMounts:
            - name: "media-pv"
              mountPath: /config
              subPath: configs/transmission-data #path /mnt/mediavolume/configs/transmission-data where transmission writes the configurations
            - name: "media-pv"
              mountPath: /downloads/transmission
              subPath: downloads/transmission # path /mnt/mediavolume/downloads/transmission where transmission downloads torrents 
            - name: "media-pv"
              mountPath: /downloads/complete
              subPath: downloads/complete # path /mnt/mediavolume/downloads/complete where transmission completes downloads 
      volumes:
        - name: "media-pv"
          persistentVolumeClaim:
            claimName: media-pv-claim
